[[redirects]]
  from = "/data/artworks.json"
  to = "/data/artworks.json"
  status = 200
  force = true

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
